fix i3 output config for work
- remove dependencies on $HOME/.functions for switch-background script
  and handle missing images

diff --git a/bin/switch-desktop-background b/bin/switch-desktop-background
--- a/bin/switch-desktop-background
+++ b/bin/switch-desktop-background
@@ -1,14 +1,25 @@
 #!/bin/bash
 
 set -e
-source "$HOME/.functions"
-BACKGROUND_IMAGE_LINK="$HOME/.current-desktop-background"
+
+BACKGROUND_IMAGE_FOLDER="$XDG_PICTURES_DIR/background_images"
+
+if [ ! -d "$BACKGROUND_IMAGE_FOLDER" ]; then
+  echo "background image folder '$BACKGROUND_IMAGE_FOLDER' not found"
+  exit 1
+fi
 
 if [ -z "$1" ]; then
-	image_file="$(random-image)"
+  image_file="$(find "$XDG_PICTURES_DIR/background_images" -type f -iname '*.png' -o -type f -iname '*.jpg' | shuf -n1)"
 else
-	image_file="$1"
+  image_file="$1"
 fi
-symlink "$image_file" "$BACKGROUND_IMAGE_LINK"
 
+if [ ! -f "$image_file" ]; then
+  echo "image file '$image_file' not found"
+  exit 1
+fi
+
+BACKGROUND_IMAGE_LINK="$HOME/.current-desktop-background"
+symlink "$image_file" "$BACKGROUND_IMAGE_LINK"
 feh --no-fehbg --bg-fill "$image_file"
